"""The written contract for a memory document.

`.kasa/schema.md` is read by two audiences: a person opening the repo, and the
consolidation model deciding what to write. It ships as prose here and becomes
generated output in #12, once the frontmatter model exists to generate it from —
a hand-maintained copy of a schema drifts from the schema, and a drifted
contract is worse than none, because the model believes it.
"""

from __future__ import annotations

SCHEMA_VERSION = 1

_SCHEMA_MD = """<!-- Generated by Kasa. Do not edit by hand. -->

# Memory document schema (v{version})

Every file under `memory/` is Markdown with a YAML frontmatter block. The
frontmatter is the contract; the body is ordinary prose written for a human.

```yaml
---
id: mem_01K8XQ4W2N7B6VJ3ZC9F0RTKME   # ULID, assigned once, never rewritten
type: person                          # person | project | topic | fact | journal
title: Deploy pipeline ownership
tags: [infra, ownership]
visibility: workspace                 # workspace | channel:C0123 | private:U0456
created: 2026-09-03T10:12:00Z
updated: 2026-09-03T10:12:00Z
confidence: 0.9                       # how sure we are this is true
salience: 0.7                         # access-weighted importance; decays
pinned: false                         # pinned memories are never forgotten
source_refs:
  - slack://T01/C0123/1756890000.123
supersedes: []                        # ids this memory replaced
---
```

## Rules

- **`id` is forever.** Files move between directories as the corpus is
  reorganized; links resolve through `.kasa/manifest.json` by id, so a moved
  file keeps every inbound link. Rewriting an id orphans them.
- **`visibility` is inherited, never widened.** A memory derived from a DM stays
  `private:`. Retrieval filters on this before ranking, so a wrong value here is
  the one bug that leaks a private conversation into a public channel.
- **One claim per memory.** Split rather than append when a file starts covering
  two subjects; the reorganizer will do it anyway, and it does it worse.
- **Link generously** with `[[mem_01K8...]]` or `[[people/jane]]`. Both forms
  resolve through the manifest.
- **Deletion is a transition, not an erasure.** A memory moves to
  `memory/archive/` first and is removed only after the retention floor. Git
  history keeps the blob either way.

## Layout

```
memory/
  README.md          generated index; the human entry point
  people/            one file per person
  projects/
  topics/
  facts/             atomic durable facts that fit nowhere else
  journal/2026/09/   nightly digests
  archive/           soft-deleted, awaiting collection
  .kasa/             generated machinery; never written by a patch plan
```
"""

_README_MD = """# Kasa long-term memory

This repository is the long-term memory of a [Kasa](https://github.com/KeunwooPark/kasa)
agent. It is the source of truth: the agent's SQLite database is a derived index
that can be deleted and rebuilt from these files at any time.

**This repository is private, and must stay private.** It accumulates whatever
the agent was told, including things said in DMs and private channels. Kasa
refuses to run against a public memory repo.

## Working with it by hand

Every memory is a Markdown file under `memory/`, and every change the agent
makes is an ordinary commit. So:

- To correct a belief, edit the file. The agent will read your version.
- To see what it decided to believe and when, read the log.
- To undo something, `git revert` it.

`memory/.kasa/schema.md` describes the frontmatter contract both you and the
agent are writing against. Everything under `.kasa/` is generated — the agent
rewrites it, so hand edits there will not survive.
"""

_INDEX_MD = """# Memory index

<!-- Kasa regenerates the listing below. Text above this comment is preserved. -->

Nothing here yet. Memories will appear as the agent promotes them out of
conversation.
"""


def render_schema_md() -> str:
    """The contract written to `.kasa/schema.md`."""
    return _SCHEMA_MD.format(version=SCHEMA_VERSION)


def render_repo_readme() -> str:
    """The repository's front page, written for the human who owns it."""
    return _README_MD


def render_memory_index() -> str:
    """The initial `memory/README.md`."""
    return _INDEX_MD
